Test PR functionality

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -32,46 +32,46 @@ jobs:
         with:
           path: ${{ env.IG_CONTAINER_PATH }}
 
-      - name: Extract IG name from canonical URL
-        run: |
-          url=$(grep '^canonical:' ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml \
-                | sed -e 's/^canonical:[[:space:]]*//')
-          IG_NAME=${url##*/}
-          echo "IG_NAME=$IG_NAME" >> $GITHUB_ENV
+      # - name: Extract IG name from canonical URL
+      #   run: |
+      #     url=$(grep '^canonical:' ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml \
+      #           | sed -e 's/^canonical:[[:space:]]*//')
+      #     IG_NAME=${url##*/}
+      #     echo "IG_NAME=$IG_NAME" >> $GITHUB_ENV
 
-      - name: Set Sushi config release YAML properties
-        uses: fjogeleit/yaml-update-action@v0.16.0
-        with:
-          valueFile: ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml
-          commitChange: false
-          createPR: false
-          changes: |
-            {
-              "version": "${{ env.RELEASE_VERSION }}",
-              "releaseLabel": "release"
-            }
+      # - name: Set Sushi config release YAML properties
+      #   uses: fjogeleit/yaml-update-action@v0.16.0
+      #   with:
+      #     valueFile: ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml
+      #     commitChange: false
+      #     createPR: false
+      #     changes: |
+      #       {
+      #         "version": "${{ env.RELEASE_VERSION }}",
+      #         "releaseLabel": "release"
+      #       }
 
-      - name: Update publication-request.json with the release version
-        run: |
-          echo "$(jq '
-            .version = env.RELEASE_VERSION |
-            .path |= sub("/[0-9\\.]+$"; "/" + env.RELEASE_VERSION)
-          ' ${{ env.IG_CONTAINER_PATH }}/publication-request.json)" > ${{ env.IG_CONTAINER_PATH }}/publication-request.json
+      # - name: Update publication-request.json with the release version
+      #   run: |
+      #     echo "$(jq '
+      #       .version = env.RELEASE_VERSION |
+      #       .path |= sub("/[0-9\\.]+$"; "/" + env.RELEASE_VERSION)
+      #     ' ${{ env.IG_CONTAINER_PATH }}/publication-request.json)" > ${{ env.IG_CONTAINER_PATH }}/publication-request.json
 
-      - name: Print edited config files
-        run: |
-          echo "======================== sushi-config.yaml        ========================"
-          cat ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml
-          echo -n "\n\n======================== publication-request.json ========================\n"
-          cat ${{ env.IG_CONTAINER_PATH }}/publication-request.json
+      # - name: Print edited config files
+      #   run: |
+      #     echo "======================== sushi-config.yaml        ========================"
+      #     cat ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml
+      #     echo -n "\n\n======================== publication-request.json ========================\n"
+      #     cat ${{ env.IG_CONTAINER_PATH }}/publication-request.json
 
-      - name: Install the latest SUSHI
-        run: npm install -g fsh-sushi
+      # - name: Install the latest SUSHI
+      #   run: npm install -g fsh-sushi
 
-      - name: Transpile to prepare for publication
-        shell: bash
-        working-directory: ${{ env.IG_CONTAINER_PATH }}
-        run: java -jar /input-cache/publisher.jar .
+      # - name: Transpile to prepare for publication
+      #   shell: bash
+      #   working-directory: ${{ env.IG_CONTAINER_PATH }}
+      #   run: java -jar /input-cache/publisher.jar .
 
       - name: Generate app token
         id: token
@@ -103,52 +103,52 @@ jobs:
             ig/${{ env.IG_NAME }}/**
             ig/templates/**
     
-      - name: Fetch the IG registry repo
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ github.repository_owner }}/${{ env.REGISTRY_REPO }}
-          token: ${{ steps.token.outputs.token }}
-          path: ${{ env.REGISTRY_REPO_CONTAINER_PATH }}
+      # - name: Fetch the IG registry repo
+      #   uses: actions/checkout@v4
+      #   with:
+      #     repository: ${{ github.repository_owner }}/${{ env.REGISTRY_REPO }}
+      #     token: ${{ steps.token.outputs.token }}
+      #     path: ${{ env.REGISTRY_REPO_CONTAINER_PATH }}
 
-      - name: Fetch the IG history template repo
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ env.IG_HISTORY_REPO }}
-          token: ${{ steps.token.outputs.token }}
-          path: ${{ env.IG_HISTORY_TEMPLATE_CONTAINER_PATH }}
+      # - name: Fetch the IG history template repo
+      #   uses: actions/checkout@v4
+      #   with:
+      #     repository: ${{ env.IG_HISTORY_REPO }}
+      #     token: ${{ steps.token.outputs.token }}
+      #     path: ${{ env.IG_HISTORY_TEMPLATE_CONTAINER_PATH }}
 
-      - name: Run the IG Publish process
-        shell: bash
-        run: >-
-          java -jar /input-cache/publisher.jar -go-publish
-          -source ${{ env.IG_CONTAINER_PATH }}
-          -web ${{ env.WEB_REPO_CONTAINER_PATH }}/ig
-          -history ${{ env.IG_HISTORY_TEMPLATE_CONTAINER_PATH }}
-          -registry ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json 
-          -templates ${{ env.WEB_REPO_CONTAINER_PATH }}/ig/templates
+      # - name: Run the IG Publish process
+      #   shell: bash
+      #   run: >-
+      #     java -jar /input-cache/publisher.jar -go-publish
+      #     -source ${{ env.IG_CONTAINER_PATH }}
+      #     -web ${{ env.WEB_REPO_CONTAINER_PATH }}/ig
+      #     -history ${{ env.IG_HISTORY_TEMPLATE_CONTAINER_PATH }}
+      #     -registry ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json 
+      #     -templates ${{ env.WEB_REPO_CONTAINER_PATH }}/ig/templates
 
-      - name: Remove unnecessary files
-        shell: bash
-        run: |
-          rm --recursive --force --verbose ${{ env.WEB_REPO_CONTAINER_PATH }}/ig/ig-build-zips
+      # - name: Remove unnecessary files
+      #   shell: bash
+      #   run: |
+      #     rm --recursive --force --verbose ${{ env.WEB_REPO_CONTAINER_PATH }}/ig/ig-build-zips
 
-      - name: Update IG registry
-        shell: bash
-        run: |
-          export DESCRIPTION=$(yq -r .description ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml)
-          export AUTHORITY=$(yq -r .publisher.name ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml)
-          echo $DESCRIPTION
-          echo $AUTHORITY
-          echo "$(jq '
-            .guides[-1].description = env.DESCRIPTION |
-            .guides[-1].authority = env.AUTHORITY |
-            .guides[-1].country = "dk"
-          ' ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json)" > ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json
+      # - name: Update IG registry
+      #   shell: bash
+      #   run: |
+      #     export DESCRIPTION=$(yq -r .description ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml)
+      #     export AUTHORITY=$(yq -r .publisher.name ${{ env.IG_CONTAINER_PATH }}/sushi-config.yaml)
+      #     echo $DESCRIPTION
+      #     echo $AUTHORITY
+      #     echo "$(jq '
+      #       .guides[-1].description = env.DESCRIPTION |
+      #       .guides[-1].authority = env.AUTHORITY |
+      #       .guides[-1].country = "dk"
+      #     ' ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json)" > ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json
 
-      - name: Show new publication IG publication registration entry
-        shell: bash
-        run: |
-          echo "$(jq '.guides[-1]' ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json)"
+      # - name: Show new publication IG publication registration entry
+      #   shell: bash
+      #   run: |
+      #     echo "$(jq '.guides[-1]' ${{ env.REGISTRY_REPO_CONTAINER_PATH }}/fhir-ig-list.json)"
 
       # ─────── 🛠️ Commit & PR ───────
       - name: Configure Git
@@ -157,19 +157,22 @@ jobs:
           git config --global user.email "${{ env.APP_AUTHOR_EMAIL }}"
 
       - name: Show Web repo git status files
+        working-directory: ${{ env.WEB_REPO_CONTAINER_PATH }}
         shell: bash
         run: |
-          git -C ${{ env.WEB_REPO_CONTAINER_PATH }} status
+          touch test.txt
+          git status
 
-      - name: Commit changes in website repo
-        working-directory: ${{ env.WEB_REPO_CONTAINER_PATH }}
-        run: |
-          git checkout -b publish-${{ env.IG_NAME }}-${{ env.RELEASE_VERSION }}
-          git add ig
-          git commit -m "chore: publish IG ${{ env.RELEASE_VERSION }}" || echo "Error - No changes to commit"
+      # - name: Commit changes in website repo
+      #   working-directory: ${{ env.WEB_REPO_CONTAINER_PATH }}
+      #   run: |
+      #     git checkout -b publish-${{ env.IG_NAME }}-${{ env.RELEASE_VERSION }}
+      #     git add ig
+      #     git commit -m "chore: publish IG ${{ env.RELEASE_VERSION }}" || echo "Error - No changes to commit"
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v4
+        working-directory: ${{ env.WEB_REPO_CONTAINER_PATH }}
         with:
           token: ${{ steps.token.outputs.token }}
           commit-message: "chore: publish IG ${{ env.RELEASE_VERSION }}"
@@ -179,4 +182,3 @@ jobs:
             This PR was automatically generated by the MedCom document publish workflow.
             It contains the transpiled IG output for version ${{ env.RELEASE_VERSION }}.
           base: main
-          path: ${{ env.WEB_REPO_CONTAINER_PATH }}
